### ISSUE TITLE
invalid signature

### ISSUE THREAD

**Issue by jimlitton** [duosecurity/duo_client_java#30]
Hi, using the cli without changes I'm seeing an invalid signature error with nfr or prod keys.  This was working with our production keys at one point (prior to the okhttp change).  I opened a support case a few days ago and am still waiting for a response.
```
java -jar duo-example-admin-0.4.1-SNAPSHOT-jar-with-dependencies.jar -host XXXXXXXXXXXXXXX.duosecurity.com -ikey XXXXXXXXXXXXXXXXXXXXXXXXX  -skey XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Duo Admin Demo
error making request
java.lang.Exception: Duo error code (40103): Invalid signature in request credentials
```

**Comment by AaronAtDuo** [comment]
@jimlitton I just tested with Admin API credentials and I was unable to reproduce the issue, so I looked into the possible causes of a 40103.  By far the most common and likely explanation is a problem with the skey.  There's a few possible issues, since we stay intentionally vague on the exact problem.  Please double check the skey from your Admin API integration, in case it was rotated, or see if there's any possible copy/paste issues.  If everything looks good, perhaps check with one of the other language repo examples... I don't believe it's a code issue but that might help narrow down the problem.

Sorry for the delay in support, but hopefully this helps focus the troubleshooting, and thanks for using Duo.

**Comment by jimlitton** [comment]
Thanks Aaron!  It is a permissions issue in the Duo Admin web console.  I am not an owner and can not see the Secret key under the Admin API but can see the key under the Web SDK.
